-- Technology - Easy (20 questions)
INSERT INTO questions (question_text, option_a, option_b, option_c, option_d, correct_answer, hint, category, difficulty) VALUES
('What does CPU stand for?', 'Central Processing Unit', 'Computer Personal Unit', 'Central Process Utility', 'Central Processor Unifier', 0, 'It\'s the brain of the computer', 'Technology', 'easy'),
('Which company created the iPhone?', 'Samsung', 'Apple', 'Google', 'Microsoft', 1, 'Think of a fruit', 'Technology', 'easy'),
('What does HTML stand for?', 'Hyper Text Markup Language', 'High Tech Multi Language', 'Hyper Text Multiple Language', 'How To Make Links', 0, 'It\'s used for creating web pages', 'Technology', 'easy'),
('What does "www" stand for in a website URL?', 'World Wide Web', 'Web World Wide', 'Wide World Web', 'World Web Wide', 0, 'It starts with "World"', 'Technology', 'easy'),
('Which of these is not an operating system?', 'Windows', 'macOS', 'Linux', 'Google Chrome', 3, 'It\'s a web browser', 'Technology', 'easy'),
('What is the main function of a router?', 'Print documents', 'Connect multiple networks', 'Store files', 'Display graphics', 1, 'It directs network traffic', 'Technology', 'easy'),
('Which device is used to input text into a computer?', 'Monitor', 'Keyboard', 'Printer', 'Speaker', 1, 'You type on it', 'Technology', 'easy'),
('What is the most common type of computer memory?', 'RAM', 'ROM', 'CPU', 'GPU', 0, 'It stands for Random Access Memory', 'Technology', 'easy'),
('Which of these is a search engine?', 'Facebook', 'Google', 'WhatsApp', 'Instagram', 1, 'It starts with G', 'Technology', 'easy'),
('What does USB stand for?', 'Universal Serial Bus', 'United Serial Bus', 'Universal System Bus', 'United System Bus', 0, 'It\'s used for connecting devices', 'Technology', 'easy'),
('Which key is used to delete text to the left of the cursor?', 'Delete', 'Enter', 'Backspace', 'Shift', 2, 'It usually has an arrow pointing left', 'Technology', 'easy'),
('What is the name of Google\'s mobile operating system?', 'iOS', 'Windows Phone', 'Android', 'BlackBerry OS', 2, 'It starts with A', 'Technology', 'easy'),
('Which social media platform limits posts to 280 characters?', 'Facebook', 'Instagram', 'Twitter', 'LinkedIn', 2, 'It features a blue bird logo', 'Technology', 'easy'),
('What is the file extension for a Word document?', '.txt', '.doc', '.jpg', '.mp3', 1, 'It starts with .doc', 'Technology', 'easy'),
('Which of these is a web browser?', 'Excel', 'PowerPoint', 'Chrome', 'Word', 2, 'It\'s developed by Google', 'Technology', 'easy'),
('What does "PDF" stand for?', 'Printable Document Format', 'Portable Document Format', 'Personal Data File', 'Public Document File', 1, 'It was created by Adobe', 'Technology', 'easy'),
('Which company owns YouTube?', 'Facebook', 'Amazon', 'Google', 'Microsoft', 2, 'It\'s the same company that owns the search engine', 'Technology', 'easy'),
('What does "Wi-Fi" stand for?', 'Wireless Fidelity', 'Wired Fiber', 'Wireless Fiber', 'Wide Fidelity', 0, 'It\'s a play on "Hi-Fi"', 'Technology', 'easy'),
('Which of these is not a programming language?', 'Python', 'Java', 'HTML', 'C++', 2, 'It\'s a markup language', 'Technology', 'easy'),
('What is the name of Apple\'s virtual assistant?', 'Alexa', 'Google Assistant', 'Siri', 'Cortana', 2, 'It was introduced on the iPhone 4S', 'Technology', 'easy');

-- Technology - Medium (20 questions)
INSERT INTO questions (question_text, option_a, option_b, option_c, option_d, correct_answer, hint, category, difficulty) VALUES
('Which programming language is known as the "mother of all languages"?', 'Java', 'C', 'Python', 'FORTRAN', 1, 'It was developed in the early 1970s', 'Technology', 'medium'),
('What does SSD stand for?', 'System Storage Drive', 'Solid State Drive', 'Secure Storage Device', 'System Software Disk', 1, 'It\'s faster than a hard drive', 'Technology', 'medium'),
('What is the name of the first widely-used graphical web browser?', 'Internet Explorer', 'Chrome', 'Mosaic', 'Firefox', 2, 'It was released in 1993', 'Technology', 'medium'),
('What does API stand for?', 'Application Programming Interface', 'Automated Program Interaction', 'Advanced Programming Interface', 'Application Process Integration', 0, 'It allows different software to communicate', 'Technology', 'medium'),
('Which of these is not a relational database management system?', 'MySQL', 'PostgreSQL', 'MongoDB', 'Oracle', 2, 'It\'s a NoSQL database', 'Technology', 'medium'),
('What is the main programming language used to develop Android apps?', 'Swift', 'Kotlin', 'C#', 'Ruby', 1, 'It was officially supported by Google in 2017', 'Technology', 'medium'),
('Which protocol is used to send email?', 'HTTP', 'FTP', 'SMTP', 'SSH', 2, 'It stands for Simple Mail Transfer Protocol', 'Technology', 'medium'),
('What does VPN stand for?', 'Virtual Private Network', 'Verified Personal Network', 'Virtual Public Network', 'Verified Private Network', 0, 'It\'s used for secure connections', 'Technology', 'medium'),
('Which company developed the Python programming language?', 'Google', 'Microsoft', 'It wasn\'t developed by a company', 'Apple', 2, 'It was created by an individual', 'Technology', 'medium'),
('What is the name of Microsoft\'s cloud computing service?', 'Google Cloud', 'AWS', 'Azure', 'IBM Cloud', 2, 'It starts with A', 'Technology', 'medium'),
('Which of these is a version control system?', 'Git', 'Java', 'Docker', 'Kubernetes', 0, 'It was created by Linus Torvalds', 'Technology', 'medium'),
('What does IoT stand for?', 'Internet of Things', 'Input of Technology', 'Internet of Technology', 'Input of Things', 0, 'It refers to connected devices', 'Technology', 'medium'),
('Which of these is a front-end web framework?', 'Django', 'Flask', 'React', 'Node.js', 2, 'It was developed by Facebook', 'Technology', 'medium'),
('What is the name of Linux\'s mascot?', 'A dog', 'A penguin', 'A dolphin', 'A fox', 1, 'It\'s Tux the penguin', 'Technology', 'medium'),
('Which company acquired GitHub in 2018?', 'Google', 'Microsoft', 'Amazon', 'Facebook', 1, 'It\'s the same company that owns Windows', 'Technology', 'medium'),
('What does CSS stand for?', 'Computer Style Sheets', 'Creative Style Sheets', 'Cascading Style Sheets', 'Colorful Style Sheets', 2, 'It\'s used for styling web pages', 'Technology', 'medium'),
('Which of these is not a JavaScript framework?', 'Angular', 'React', 'Vue', 'Django', 3, 'It\'s a Python framework', 'Technology', 'medium'),
('What is the name of Apple\'s proprietary processor architecture?', 'Intel', 'AMD', 'ARM', 'M1', 3, 'It was introduced in 2020', 'Technology', 'medium'),
('Which technology is used to create decentralized applications?', 'Cloud Computing', 'Blockchain', 'Artificial Intelligence', 'Virtual Reality', 1, 'It\'s the technology behind cryptocurrencies', 'Technology', 'medium'),
('What does IDE stand for?', 'Integrated Development Environment', 'Interactive Development Engine', 'International Data Exchange', 'Integrated Data Environment', 0, 'It\'s where programmers write code', 'Technology', 'medium');


INSERT INTO questions (question_text, option_a, option_b, option_c, option_d, correct_answer, hint, category, difficulty) VALUES
('In which year was the first .com domain registered?', '1985', '1991', '1980', '1995', 0, 'It was in the mid-1980s', 'Technology', 'hard'),
('What was the name of the first computer programmer?', 'Alan Turing', 'Ada Lovelace', 'Grace Hopper', 'Charles Babbage', 1, 'She worked with Charles Babbage', 'Technology', 'hard'),
('Which protocol is used to securely transfer files between a client and a server?', 'HTTP', 'FTP', 'SMTP', 'SFTP', 3, 'It\'s a secure version of a file transfer protocol', 'Technology', 'hard'),
('What was the first object-oriented programming language?', 'C++', 'Java', 'Simula', 'Smalltalk', 2, 'It was developed in the 1960s', 'Technology', 'hard'),
('Which of these is not a type of machine learning?', 'Supervised learning', 'Unsupervised learning', 'Reinforcement learning', 'Compiler learning', 3, 'It\'s not a learning paradigm', 'Technology', 'hard'),
('What was the name of the first computer virus?', 'ILOVEYOU', 'MyDoom', 'Creeper', 'Melissa', 2, 'It was created in the early 1970s', 'Technology', 'hard'),
('Which company developed the first commercial GUI operating system?', 'Microsoft', 'Apple', 'Xerox', 'IBM', 2, 'It was the Xerox Alto', 'Technology', 'hard'),
('What does NP stand for in NP-complete problems?', 'Non-Polynomial', 'Non-Deterministic Polynomial', 'Numerical Polynomial', 'Network Polynomial', 1, 'It relates to computational complexity', 'Technology', 'hard'),
('Which of these is not a design pattern?', 'Singleton', 'Observer', 'Factory', 'Compiler', 3, 'It\'s not a software design pattern', 'Technology', 'hard'),
('What was the first message sent over ARPANET?', 'Hello world', 'Welcome', 'Lo', 'Testing', 2, 'It was the first two letters of "login"', 'Technology', 'hard'),
('Which algorithm is used for Bitcoin mining?', 'SHA-256', 'MD5', 'AES', 'RSA', 0, 'It\'s a cryptographic hash function', 'Technology', 'hard'),
('What was the first web browser called?', 'Netscape', 'WorldWideWeb', 'Internet Explorer', 'Mosaic', 1, 'It was created by Tim Berners-Lee', 'Technology', 'hard'),
('Which of these is not a type of SQL join?', 'INNER JOIN', 'OUTER JOIN', 'CROSS JOIN', 'VERTICAL JOIN', 3, 'It\'s not a standard join operation', 'Technology', 'hard'),
('What does CAP stand for in the CAP theorem?', 'Consistency, Availability, Partition tolerance', 'Compute, Access, Performance', 'Control, Access, Performance', 'Consistency, Access, Partition tolerance', 0, 'It\'s a distributed systems theorem', 'Technology', 'hard'),
('Which company developed the first commercial microprocessor?', 'Intel', 'AMD', 'IBM', 'Texas Instruments', 0, 'It was the Intel 4004', 'Technology', 'hard'),
('What is the name of the first computer that used stored programs?', 'ENIAC', 'UNIVAC', 'EDSAC', 'Colossus', 2, 'It was developed at Cambridge University', 'Technology', 'hard'),
('Which of these is not a type of blockchain consensus mechanism?', 'Proof of Work', 'Proof of Stake', 'Proof of Authority', 'Proof of Concept', 3, 'It\'s not a consensus algorithm', 'Technology', 'hard'),
('What was the first programming language to implement object-oriented programming?', 'C++', 'Simula', 'Smalltalk', 'Java', 1, 'It was developed in Norway', 'Technology', 'hard'),
('Which of these is not a NoSQL database type?', 'Document', 'Key-value', 'Graph', 'Hierarchical', 3, 'It\'s not a NoSQL category', 'Technology', 'hard'),
('What does ACID stand for in database transactions?', 'Atomicity, Consistency, Isolation, Durability', 'Accuracy, Consistency, Integrity, Durability', 'Atomicity, Consistency, Integrity, Durability', 'Accuracy, Concurrency, Isolation, Durability', 0, 'It\'s a set of database properties', 'Technology', 'hard');

-- General Knowledge - Easy (20 questions)
INSERT INTO questions (question_text, option_a, option_b, option_c, option_d, correct_answer, hint, category, difficulty) VALUES
('What is the capital of France?', 'London', 'Paris', 'Berlin', 'Rome', 1, 'It\'s known as the City of Light', 'General', 'easy'),
('Which planet is known as the Red Planet?', 'Jupiter', 'Venus', 'Mars', 'Saturn', 2, 'It\'s named after the Roman god of war', 'General', 'easy'),
('How many sides does a hexagon have?', 'Five', 'Six', 'Seven', 'Eight', 1, 'Think about the prefix "hexa"', 'General', 'easy'),
('What is the largest mammal in the world?', 'Elephant', 'Blue whale', 'Giraffe', 'Polar bear', 1, 'It lives in the ocean', 'General', 'easy'),
('Which country is home to the kangaroo?', 'South Africa', 'Brazil', 'Australia', 'India', 2, 'It\'s also home to the koala', 'General', 'easy'),
('What is the longest river in the world?', 'Amazon', 'Nile', 'Yangtze', 'Mississippi', 1, 'It\'s in Africa', 'General', 'easy'),
('How many colors are in a rainbow?', 'Five', 'Six', 'Seven', 'Eight', 2, 'Remember the acronym ROYGBIV', 'General', 'easy'),
('Which of these is not a primary color?', 'Red', 'Blue', 'Green', 'Yellow', 2, 'In traditional color theory', 'General', 'easy'),
('What is the largest ocean on Earth?', 'Atlantic', 'Indian', 'Arctic', 'Pacific', 3, 'It covers about one-third of Earth\'s surface', 'General', 'easy'),
('Which of these is not a continent?', 'Africa', 'Europe', 'Asia', 'Arctic', 3, 'It\'s an ocean', 'General', 'easy'),
('What is the capital of Japan?', 'Beijing', 'Seoul', 'Tokyo', 'Bangkok', 2, 'It\'s a populous city in East Asia', 'General', 'easy'),
('Which of these is not a fruit?', 'Tomato', 'Carrot', 'Pumpkin', 'Cucumber', 1, 'It grows underground', 'General', 'easy'),
('How many days are in a leap year?', '365', '366', '364', '367', 1, 'February has an extra day', 'General', 'easy'),
('What is the tallest mountain in the world?', 'K2', 'Mount Everest', 'Kilimanjaro', 'Denali', 1, 'It\'s in the Himalayas', 'General', 'easy'),
('Which of these is not a planet in our solar system?', 'Mercury', 'Venus', 'Pluto', 'Mars', 2, 'It was reclassified as a dwarf planet', 'General', 'easy'),
('What is the currency of the United Kingdom?', 'Euro', 'Dollar', 'Pound', 'Yen', 2, 'It\'s also called sterling', 'General', 'easy'),
('Which animal is known as the "King of the Jungle"?', 'Elephant', 'Lion', 'Tiger', 'Gorilla', 1, 'It has a large mane', 'General', 'easy'),
('What is the largest desert in the world?', 'Sahara', 'Gobi', 'Arabian', 'Antarctic', 3, 'It\'s a cold desert', 'General', 'easy'),
('Which of these is not a bone in the human body?', 'Femur', 'Humerus', 'Tibia', 'Liver', 3, 'It\'s an organ', 'General', 'easy'),
('What is the main language spoken in Brazil?', 'Spanish', 'Portuguese', 'English', 'French', 1, 'It\'s a Romance language', 'General', 'easy');

-- General Knowledge - Medium (20 questions)
INSERT INTO questions (question_text, option_a, option_b, option_c, option_d, correct_answer, hint, category, difficulty) VALUES
('Which element has the chemical symbol Au?', 'Silver', 'Gold', 'Aluminum', 'Argon', 1, 'It comes from the Latin word "aurum"', 'General', 'medium'),
('Who painted the Mona Lisa?', 'Vincent van Gogh', 'Pablo Picasso', 'Leonardo da Vinci', 'Michelangelo', 2, 'He was an Italian Renaissance polymath', 'General', 'medium'),
('In which year did World War II end?', '1943', '1945', '1947', '1950', 1, 'It was in the mid-1940s', 'General', 'medium'),
('Which country gifted the Statue of Liberty to the United States?', 'Spain', 'England', 'France', 'Italy', 2, 'It was a gift commemorating the alliance during the American Revolution', 'General', 'medium'),
('What is the largest organ in the human body?', 'Heart', 'Liver', 'Skin', 'Lungs', 2, 'It covers your entire body', 'General', 'medium'),
('Which of these languages is written from right to left?', 'Chinese', 'Arabic', 'Russian', 'Spanish', 1, 'It\'s a Semitic language', 'General', 'medium'),
('Who wrote "Romeo and Juliet"?', 'Charles Dickens', 'William Shakespeare', 'Jane Austen', 'Mark Twain', 1, 'He was an English playwright', 'General', 'medium'),
('Which planet has the most moons?', 'Jupiter', 'Saturn', 'Neptune', 'Mars', 1, 'As of 2023, it has over 80 confirmed moons', 'General', 'medium'),
('What is the capital of Canada?', 'Toronto', 'Vancouver', 'Ottawa', 'Montreal', 2, 'It\'s in the province of Ontario', 'General', 'medium'),
('Which of these is not one of the Seven Wonders of the Ancient World?', 'Great Pyramid of Giza', 'Hanging Gardens of Babylon', 'Colossus of Rhodes', 'Eiffel Tower', 3, 'It was built in the 19th century', 'General', 'medium'),
('What is the smallest country in the world?', 'Monaco', 'Vatican City', 'San Marino', 'Liechtenstein', 1, 'It\'s the headquarters of the Catholic Church', 'General', 'medium'),
('Which blood type is known as the universal donor?', 'A', 'B', 'AB', 'O', 3, 'It\'s the most common blood type', 'General', 'medium'),
('Who was the first woman to win a Nobel Prize?', 'Marie Curie', 'Rosalind Franklin', 'Florence Nightingale', 'Mother Teresa', 0, 'She won it in Physics', 'General', 'medium'),
('Which country invented tea?', 'India', 'England', 'China', 'Japan', 2, 'It has a long history dating back thousands of years', 'General', 'medium'),
('What is the name of the currency used in Germany?', 'Pound', 'Franc', 'Euro', 'Mark', 2, 'It\'s used by many European countries', 'General', 'medium'),
('Which of these is not a Shakespeare play?', 'Macbeth', 'Hamlet', 'Romeo and Juliet', 'Pride and Prejudice', 3, 'It was written by Jane Austen', 'General', 'medium'),
('What is the name of the longest river in South America?', 'Amazon', 'Nile', 'Mississippi', 'Yangtze', 0, 'It flows through Brazil', 'General', 'medium'),
('Which country has the most time zones?', 'United States', 'Russia', 'China', 'France', 3, 'Due to its overseas territories', 'General', 'medium'),
('Who discovered penicillin?', 'Alexander Fleming', 'Louis Pasteur', 'Marie Curie', 'Albert Einstein', 0, 'It was an accidental discovery', 'General', 'medium'),
('Which of these is not a type of cloud?', 'Cumulus', 'Stratus', 'Cirrus', 'Solidus', 3, 'It\'s a Latin term used in other contexts', 'General', 'medium');

-- General Knowledge - Hard (20 questions)
INSERT INTO questions (question_text, option_a, option_b, option_c, option_d, correct_answer, hint, category, difficulty) VALUES
('What is the smallest prime number?', '0', '1', '2', '3', 2, 'It\'s the only even prime number', 'General', 'hard'),
('Which country has the most islands in the world?', 'Indonesia', 'Philippines', 'Sweden', 'Norway', 2, 'It\'s a Scandinavian country', 'General', 'hard'),
('What is the hardest natural substance on Earth?', 'Titanium', 'Diamond', 'Platinum', 'Quartz', 1, 'It\'s made of carbon', 'General', 'hard'),
('Which planet in our solar system rotates on its side?', 'Venus', 'Mars', 'Uranus', 'Neptune', 2, 'Its axis is tilted at about 98 degrees', 'General', 'hard'),
('What is the only mammal capable of true flight?', 'Bat', 'Flying squirrel', 'Penguin', 'Ostrich', 0, 'It uses echolocation', 'General', 'hard'),
('Which country has the longest coastline?', 'Russia', 'Canada', 'Australia', 'United States', 1, 'It borders three oceans', 'General', 'hard'),
('What is the name of the smallest bone in the human body?', 'Femur', 'Stapes', 'Tibia', 'Humerus', 1, 'It\'s in the ear', 'General', 'hard'),
('Which ancient wonder was located in Babylon?', 'Great Pyramid', 'Hanging Gardens', 'Colossus', 'Lighthouse of Alexandria', 1, 'It was supposedly built by Nebuchadnezzar II', 'General', 'hard'),
('What is the only letter that doesn\'t appear in any U.S. state name?', 'X', 'Q', 'Z', 'J', 1, 'It\'s the 17th letter of the alphabet', 'General', 'hard'),
('Which country has the most pyramids?', 'Egypt', 'Mexico', 'Sudan', 'Peru', 2, 'They\'re located in the Nubian region', 'General', 'hard'),
('What is the name of the world\'s largest coral reef system?', 'Great Barrier Reef', 'Belize Barrier Reef', 'New Caledonia Barrier Reef', 'Red Sea Coral Reef', 0, 'It\'s off the coast of Australia', 'General', 'hard'),
('Which planet has the longest day?', 'Mercury', 'Venus', 'Earth', 'Mars', 1, 'A day is longer than its year', 'General', 'hard'),
('What is the name of the deepest part of the world\'s oceans?', 'Mariana Trench', 'Puerto Rico Trench', 'Java Trench', 'Philippine Trench', 0, 'It\'s in the western Pacific', 'General', 'hard'),
('Which country was the first to give women the right to vote?', 'United States', 'United Kingdom', 'New Zealand', 'Sweden', 2, 'It was in 1893', 'General', 'hard'),
('What is the name of the first cloned mammal?', 'Dolly the sheep', 'Molly the cow', 'Polly the parrot', 'Holly the horse', 0, 'It was cloned in 1996', 'General', 'hard'),
('Which element is liquid at room temperature?', 'Bromine', 'Mercury', 'Gallium', 'All of the above', 3, 'They all have low melting points', 'General', 'hard'),
('What is the name of the world\'s largest desert?', 'Sahara', 'Arabian', 'Antarctic', 'Gobi', 2, 'It\'s a cold desert', 'General', 'hard'),
('Which country has the most active volcanoes?', 'Japan', 'Indonesia', 'United States', 'Chile', 1, 'It\'s part of the Pacific Ring of Fire', 'General', 'hard'),
('What is the name of the first human to journey into outer space?', 'Neil Armstrong', 'Yuri Gagarin', 'Alan Shepard', 'John Glenn', 1, 'He was Soviet cosmonaut', 'General', 'hard'),
('Which of these countries was never part of the British Empire?', 'United States', 'India', 'Thailand', 'Australia', 2, 'It\'s in Southeast Asia', 'General', 'hard');