services:
  - type: web
    name: quiz404
    env: docker
    plan: free
    dockerfilePath: Dockerfile
    envVars:
      - key: DB_HOST
        value: your-db-host
      - key: DB_NAME
        value: quiz404
      - key: DB_USER
        value: your-db-username
      - key: DB_PASSWORD
        value: your-db-password
    healthCheckPath: /
